### ISSUE TITLE
Can't compile STM32f4_discovery examples

### ISSUE THREAD

**Issue by ayoubSoussi** [modm-io/modm#516] opened 2020-12-08 18:35 UTC
Hi,
I'm trying to compile an example of the modm library to get started with it, but I found some errors during the build. I had the same errors in 2 different examples : stm32f4_discovery/blink and stm32f4_discovery/uart.

### Problem : 
Using the commands
`make cmake`
`make build`
I get the errors
![bug](https://user-images.githubusercontent.com/34512229/101525431-9d772280-398b-11eb-81d9-9ffc5618835e.png)
  
Saying that __get_BASEPRI, __set_BASEPRI_MAX, __set_BASEPRI were not declared.

I think that the examples in this folder are out-of-date (if it's the case, I would like to get a hint to what to do and I can update the examples).

Thanks.

**Comment by salkinium** [comment] 2020-12-08 18:58
You need to do `make cmake` once, then you can do `make build`.

We should make the Makefile `cmake` target depend on the actual folders, so that the cmake part get's automatically build on `make build`.

**Comment by ayoubSoussi** [comment] 2020-12-08 19:08
of course I did a `make cmake`, then a `make build` but I still get the error

**Comment by rleh** [comment] 2020-12-08 19:16
What operation system are you using?
Which GCC version (`arm-none-eabi-g++ --version`) do you use?

**Comment by ayoubSoussi** [comment] 2020-12-08 19:28
I use Ubuntu 18.04.5 LTS
My GCC version is : 9.3.1

## Update : 
I was able to compile and generate the bin and hex files using this combination of commands
`make cmake`
`make build ` (it still gives the error I described earlier)
`make all`

**Comment by rleh** [comment] 2020-12-08 19:31
I can't reproduce the error on my Fedora Linux system, but get another error:
```bash
...
arm-none-eabi-objdump: DWARF error: could not find variable specification at offset 20cd
arm-none-eabi-objdump: DWARF error: could not find variable specification at offset 964
arm-none-eabi-objdump: DWARF error: could not find variable specification at offset 973
arm-none-eabi-objdump: DWARF error: could not find variable specification at offset 1a0e
arm-none-eabi-objdump: DWARF error: could not find variable specification at offset 1a1d
...
```

~On Ubuntu 20.04 is get the following error: [...]~
Works fine after following the installation guide https://modm.io/guide/installation/.

**Comment by salkinium** [comment] 2020-12-08 19:43
(On macOS it works fine, with arm-none-eabi-gcc 9.3.1 and cmake 3.18.2)

**Comment by ayoubSoussi** [comment] 2020-12-08 20:00
It works fine also in Ubuntu 18.04 but with the combination of commands that I described in the previous comment.

**Comment by salkinium** [comment] 2021-03-29 13:49
I'm closing this issue since we cannot reproduce this bug and you seem to have found a workaround.

**Closed as completed by salkinium** 2021-03-29 13:49 UTC
Labels: bug 🐞, help wanted 🛠, toolchain ⚙️
