### ISSUE TITLE
Docs Page, Search Function is Intermittent?

### ISSUE THREAD

**Issue by thestumbler** [modm-io/modm#1078] opened 2023-09-13 08:45 UTC
Maybe it's something on my side, but I can rarely get the search function to work on the docs page. By work I mean return any results. It does rarely pop up a result, and at first I thought maybe the search was restricted to whatever "chapter" I'm in at the moment. But that doesn't seem to be true. 

Well, just now as I'm trying to find an example, it's suddenly working again. And the scope of the search doesn't appear to matter where you are in the document. So, this is not a bug, unless it comes back again.

**Comment by rleh** [comment] 2023-09-13 08:59
> the docs page

Are you referring to https://modm.io or https://docs.modm.io?

**Comment by thestumbler** [comment] 2023-09-13 09:00
Ah, sorry, I wasn't clear. The latter, docs.modm.io

**Comment by rleh** [comment] 2023-09-13 09:09
I can't reproduce the problem, at least for the F469-Disco and Nucleo-G474 board targets.

While the documentation is updated (after a pull request is merged) https://docs.modm.io/ is in an inconsistent state for 1-3 minutes while unpacking/installing the new files.
Maybe you caught just such a moment?

**Comment by thestumbler** [comment] 2023-09-13 09:14
Maybe so, that sounds typical for my luck. 8-)
It I notice it again, I'll shoot a quick message.

**Closed as completed** 2023-09-13 09:16 UTC
Labels: wontfix 😱

**Comment by salkinium** [comment] 2023-09-13 18:10
The search is completely client-side, so if you have an adblocker or something that blocks Javascript, that may interfere?

**Comment by thestumbler** [comment] 2023-09-13 20:16
Ad blocker, I suppose that's possible. I'm running Safari most of the time but don't take any extraordinary anti-ad steps (to my recollection). I will check this however. I jump between two or more computers and maybe that could be the culprit. 

In the meantime, I keep a couple of TMUX windows open dedicated to the base MODM and the project-generated MODM. That, and a lot of FIND and GREP commands do the trick. In VSCODE I can easily jump around in the generated MODM.
